### ISSUE TITLE
사업 모델

### ISSUE THREAD

**Issue by lani009** [lani009/Ajou-capstone-Fashion-AI#2]
# 사업 모델
커뮤니티 마련 (사람 팔로우, 해시태그 팔로우)

### 게시글
좋아요, 댓글, 해시태그 + 인스타 내 기능 벤치마크

### 광고 피드
광고

### Try It On
게시글의 옷을 내가 가상으로 입어볼 수 있음.

### 판매 기능
판매할 수 있음. + 돈받음

**Comment by pengm2ng** [comment]
# 보고서에 쓸 사업 모델의 내용
단지 나의 생각

## 카메라(?) 앱을 통한 수익 모델
1. 기능 사용 시 광고 시청
2, 관련 의료 어플 추천 기능을 통한 수수료 get

## 이후 커뮤니티 개발
카메라 앱이 반응이 좋을 경우 커뮤니티 개발
커뮤니티를 통한 수익 모델은 위 issue 에서 확인 바람

## 사업의 확장 가능성 제시
카메라 앱을 통해 창업 회사의 인지도를 올린 후 커뮤니티 추가, 관련 다른 앱을 개발 하는 등의 향후 활동 제시
*애플리케이션 개발 기업은 처음부터 수익모델을 갖고 시작하는 것이 아니라 꾸준히 수익 모델을 찾아가는 것이 중요.
ex) 페이스북, 카카오톡
