### ISSUE TITLE
보고서

### ISSUE THREAD

**Issue by pengm2ng** [lani009/Ajou-capstone-Fashion-AI#3]
# 보고서

## 1. 창업의 목표
- 어떤 기업을 목표로 하나

## 2. 사업 아이템 
- 우리가 만들 애플리케이션 설명 -> #2 
- 사업 모델 -> #2 
- 다이어그램 

## 3. 사업 아이템에 필요한 기술
 - ex) GAN, mmfashion, computer vision...
- 기술에 대한 세부 설명 필요

## 5. 발전 방향
- 빅 픽쳐 설명

**Comment by pengm2ng** [comment]
# 고려해야할 사항
## gan -> 갤러리에 있는 사진을 통해 비슷한 옷을 만드는 기술이 꼭 필요한가?
- 비슷한 옷을 제공해서 사람들의 선택의 폭을 넓혀줄 것인가?
- mmfashion으로 갤러리에 있는 사진이랑 비슷한 옷을 찾아서 추천해주는 기능을 통해서도 gan 기능을 cover 할 수 있는가?
2번이 가능하다면 1번을 꼭 할 필요는 없을 것 같음

## 우리의 기술이 기존 기술과 어떤 차별성을 가지는가?
- 여러 패션, 마켓 애플리케이션에서는 이미 비슷한 상품을 추천해주는 기능이 존재
- 이미지 검색을 통해서 구글에서 검색이 가능함 (https://www.google.com/search?tbs=sbi:AMhZZitsZwrDVwpoLV3Qt3-K1fW6dtC6UY2aZccSSjI1WLlthc4DuAIeQuaF5fjMkr_16RW_1rnYKfLEqaTIA5tVNI-LBZvpaLEsGaO5Gghv1nhVpTWiWiBiqWbzBLQetjPsQ_13UmW_1G0PMJvbhsfNwJPvdA5q05K1jodt-iwG4w3yU3Vj4NILKiXtdGTfO6bzJgQbwLF5uYOcDB2lOINcHWriHj8q0v2Pu4cb-V_1A16apC2TRzE3jMw-ZFiWtQkYNXIzsl20Vb9bnzWAhIqeM_1QK6zpTY0Ok7RhsrV56imkEXtBtJZFOdN29BCJV-qHG_1tg9dYdCmNq7x-uuYByYVE4VId9tH8zqIYw&btnG=%EC%9D%B4%EB%AF%B8%EC%A7%80%EB%A1%9C%20%EA%B2%80%EC%83%89&hl=ko)

## 차별성
- 이미지 검색을 통해 패션 사이트들로의 빠른 연결 제공
- 해당 사이트들의 이미지를 불러와서 옷 입히기 기능을 제공 (여러 장의 이미지로 제공)
  - 사이트 추천 시 화면 구성
  1. 사이트로의 연결
  2. 제품 사진 불러와서 내 사진에 입혀보기

## 또 다른 기능이나 차별성에 대해 생각해봐야 할 듯,,,

**Comment by lani009** [comment]
위 이슈의 2번 대목
# 이미지 검색이 가능하다면...
이미지 검색으로 유사한 이미지를 검색할 수는 있으나, 구매링크로 직접적인 연결은 되어 있지 않음. + 쇼핑몰과 api를 통해 연결된게 아니라, 구글의 크롤링으로 완성된 기능이기 때문에 검색이 안되는 옷을도 있을 것임.

# 차별점
아마도.

비슷한 옷을 찾아주는 기능을 통해서 쇼핑몰 구매링크 까지 이어줄 수 있다면 차별성이 있을 것 같기도 함. + 다나와 처럼 입점 수수료를 받는 것도 사업모델이 될 수도 있을 것 같음.

**Comment by pengm2ng** [comment]
# 기능 추가 idea

## 저장 기능
내가 마음에 든 옷을 이미지로 모아두고 최적의 조합을 추천해주는 기능 -> 핏 구별 x, mmfashion 기능으로?
